export const AIRPORT = [
  {
    coordinates: {
      latitude: 17.2403,
      longitude: 78.4294,
    },
    additional_info: {
      timezone: "IST",
      elevation: 617,
    },
    _id: "6514309e348f6fafa1b86600",
    name: "Rajiv Gandhi International Airport",
    city: "Hyderabad",
    country: "India",
    iata_code: "HYD",
    icao_code: "VOHS",
    __v: 0,
  },
  {
    coordinates: {
      latitude: 23.0738,
      longitude: 72.6347,
    },
    additional_info: {
      timezone: "IST",
      elevation: 55,
    },
    _id: "6514309e348f6fafa1b86601",
    name: "Sardar Vallabhbhai Patel International Airport",
    city: "Ahmedabad",
    country: "India",
    iata_code: "AMD",
    icao_code: "VAAH",
    __v: 0,
  },
  {
    coordinates: {
      latitude: 15.3801,
      longitude: 73.8314,
    },
    additional_info: {
      timezone: "IST",
      elevation: 56,
    },
    _id: "6514309e348f6fafa1b86602",
    name: "Goa International Airport",
    city: "Goa",
    country: "India",
    iata_code: "GOI",
    icao_code: "VOGO",
    __v: 0,
  },
  {
    coordinates: {
      latitude: 18.5821,
      longitude: 73.9197,
    },
    additional_info: {
      timezone: "IST",
      elevation: 592,
    },
    _id: "6514309e348f6fafa1b86603",
    name: "Pune Airport",
    city: "Pune",
    country: "India",
    iata_code: "PNQ",
    icao_code: "VAPO",
    __v: 0,
  },
  {
    coordinates: {
      latitude: 26.1061,
      longitude: 91.5859,
    },
    additional_info: {
      timezone: "IST",
      elevation: 49,
    },
    _id: "6514309e348f6fafa1b86604",
    name: "Lokpriya Gopinath Bordoloi International Airport",
    city: "Guwahati",
    country: "India",
    iata_code: "GAU",
    icao_code: "VEGT",
    __v: 0,
  },
  {
    coordinates: {
      latitude: 26.8242,
      longitude: 75.8122,
    },
    additional_info: {
      timezone: "IST",
      elevation: 385,
    },
    _id: "6514309e348f6fafa1b86605",
    name: "Jaipur International Airport",
    city: "Jaipur",
    country: "India",
    iata_code: "JAI",
    icao_code: "VIJP",
    __v: 0,
  },
  {
    coordinates: {
      latitude: 21.0922,
      longitude: 79.0472,
    },
    additional_info: {
      timezone: "IST",
      elevation: 315,
    },
    _id: "6514309e348f6fafa1b86606",
    name: "Dr. Babasaheb Ambedkar International Airport",
    city: "Nagpur",
    country: "India",
    iata_code: "NAG",
    icao_code: "VANP",
    __v: 0,
  },
  {
    coordinates: {
      latitude: 28.5562,
      longitude: 77.1,
    },
    additional_info: {
      timezone: "IST",
      elevation: 237,
    },
    _id: "6514309e348f6fafa1b86607",
    name: "Indira Gandhi International Airport",
    city: "Delhi",
    country: "India",
    iata_code: "DEL",
    icao_code: "VIDP",
    __v: 0,
  },
  {
    coordinates: {
      latitude: 19.0896,
      longitude: 72.8656,
    },
    additional_info: {
      timezone: "IST",
      elevation: 14,
    },
    _id: "6514309e348f6fafa1b86608",
    name: "Chhatrapati Shivaji Maharaj International Airport",
    city: "Mumbai",
    country: "India",
    iata_code: "BOM",
    icao_code: "VABB",
    __v: 0,
  },
  {
    coordinates: {
      latitude: 13.1986,
      longitude: 77.7066,
    },
    additional_info: {
      timezone: "IST",
      elevation: 915,
    },
    _id: "6514309e348f6fafa1b86609",
    name: "Kempegowda International Airport",
    city: "Bengaluru",
    country: "India",
    iata_code: "BLR",
    icao_code: "VOBL",
    __v: 0,
  },
  {
    coordinates: {
      latitude: 22.6547,
      longitude: 88.4467,
    },
    additional_info: {
      timezone: "IST",
      elevation: 5,
    },
    _id: "6514309e348f6fafa1b8660a",
    name: "Netaji Subhas Chandra Bose International Airport",
    city: "Kolkata",
    country: "India",
    iata_code: "CCU",
    icao_code: "VECC",
    __v: 0,
  },
  {
    coordinates: {
      latitude: 12.9941,
      longitude: 80.1709,
    },
    additional_info: {
      timezone: "IST",
      elevation: 16,
    },
    _id: "6514309e348f6fafa1b8660b",
    name: "Chennai International Airport",
    city: "Chennai",
    country: "India",
    iata_code: "MAA",
    icao_code: "VOMM",
    __v: 0,
  },
  {
    coordinates: {
      latitude: 10.1519,
      longitude: 76.4019,
    },
    additional_info: {
      timezone: "IST",
      elevation: 5,
    },
    _id: "6514309e348f6fafa1b8660c",
    name: "Cochin International Airport",
    city: "Kochi",
    country: "India",
    iata_code: "COK",
    icao_code: "VOCI",
    __v: 0,
  },
  {
    coordinates: {
      latitude: 30.6733,
      longitude: 76.7886,
    },
    additional_info: {
      timezone: "IST",
      elevation: 309,
    },
    _id: "6514309e348f6fafa1b8660d",
    name: "Chandigarh International Airport",
    city: "Chandigarh",
    country: "India",
    iata_code: "IXC",
    icao_code: "VICG",
    __v: 0,
  },
  {
    coordinates: {
      latitude: 20.2444,
      longitude: 85.8178,
    },
    additional_info: {
      timezone: "IST",
      elevation: 40,
    },
    _id: "6514309e348f6fafa1b8660e",
    name: "Biju Patnaik International Airport",
    city: "Bhubaneswar",
    country: "India",
    iata_code: "BBI",
    icao_code: "VEBS",
    __v: 0,
  },
  {
    coordinates: {
      latitude: 11.0291,
      longitude: 77.0434,
    },
    additional_info: {
      timezone: "IST",
      elevation: 396,
    },
    _id: "6514309e348f6fafa1b8660f",
    name: "Coimbatore International Airport",
    city: "Coimbatore",
    country: "India",
    iata_code: "CJB",
    icao_code: "VOCB",
    __v: 0,
  },
  {
    coordinates: {
      latitude: 26.7606,
      longitude: 80.8893,
    },
    additional_info: {
      timezone: "IST",
      elevation: 123,
    },
    _id: "6514309e348f6fafa1b86610",
    name: "Lucknow International Airport",
    city: "Lucknow",
    country: "India",
    iata_code: "LKO",
    icao_code: "VILK",
    __v: 0,
  },
  {
    coordinates: {
      latitude: 8.4821,
      longitude: 76.92,
    },
    additional_info: {
      timezone: "IST",
      elevation: 5,
    },
    _id: "6514309e348f6fafa1b86611",
    name: "Trivandrum International Airport",
    city: "Thiruvananthapuram",
    country: "India",
    iata_code: "TRV",
    icao_code: "VOTV",
    __v: 0,
  },
  {
    coordinates: {
      latitude: 12.9613,
      longitude: 74.8901,
    },
    additional_info: {
      timezone: "IST",
      elevation: 102,
    },
    _id: "6514309e348f6fafa1b86612",
    name: "Mangalore International Airport",
    city: "Mangalore",
    country: "India",
    iata_code: "IXE",
    icao_code: "VOML",
    __v: 0,
  },
  {
    coordinates: {
      latitude: 31.7057,
      longitude: 74.7994,
    },
    additional_info: {
      timezone: "IST",
      elevation: 230,
    },
    _id: "6514309e348f6fafa1b86613",
    name: "Amritsar International Airport",
    city: "Amritsar",
    country: "India",
    iata_code: "ATQ",
    icao_code: "VIAR",
    __v: 0,
  },
  {
    coordinates: {
      latitude: 30.1901,
      longitude: 78.1803,
    },
    additional_info: {
      timezone: "IST",
      elevation: 558,
    },
    _id: "6514309e348f6fafa1b86614",
    name: "Dehradun Airport",
    city: "Dehradun",
    country: "India",
    iata_code: "DED",
    icao_code: "VIDN",
    __v: 0,
  },
  {
    coordinates: {
      latitude: 22.3362,
      longitude: 73.2263,
    },
    additional_info: {
      timezone: "IST",
      elevation: 39,
    },
    _id: "6514309e348f6fafa1b86615",
    name: "Vadodara Airport",
    city: "Vadodara",
    country: "India",
    iata_code: "BDQ",
    icao_code: "VABO",
    __v: 0,
  },
  {
    coordinates: {
      latitude: 9.8345,
      longitude: 78.0934,
    },
    additional_info: {
      timezone: "IST",
      elevation: 139,
    },
    _id: "6514309e348f6fafa1b86616",
    name: "Madurai Airport",
    city: "Madurai",
    country: "India",
    iata_code: "IXM",
    icao_code: "VOMD",
    __v: 0,
  },
  {
    coordinates: {
      latitude: 25.5941,
      longitude: 85.1376,
    },
    additional_info: {
      timezone: "IST",
      elevation: 52,
    },
    _id: "6514309e348f6fafa1b86617",
    name: "Lok Nayak Jayaprakash Airport",
    city: "Patna",
    country: "India",
    iata_code: "PAT",
    icao_code: "VEPT",
    __v: 0,
  },
  {
    coordinates: {
      latitude: 34.1359,
      longitude: 77.5465,
    },
    additional_info: {
      timezone: "IST",
      elevation: 3256,
    },
    _id: "6514309e348f6fafa1b86618",
    name: "Kushok Bakula Rimpochee Airport",
    city: "Leh",
    country: "India",
    iata_code: "IXL",
    icao_code: "VILH",
    __v: 0,
  },
  {
    coordinates: {
      latitude: 23.8865,
      longitude: 91.2405,
    },
    additional_info: {
      timezone: "IST",
      elevation: 14,
    },
    _id: "6514309e348f6fafa1b86619",
    name: "Agartala Airport",
    city: "Agartala",
    country: "India",
    iata_code: "IXA",
    icao_code: "VEAT",
    __v: 0,
  },
  {
    coordinates: {
      latitude: 24.7443,
      longitude: 84.9512,
    },
    additional_info: {
      timezone: "IST",
      elevation: 116,
    },
    _id: "6514309e348f6fafa1b8661a",
    name: "Gaya Airport",
    city: "Gaya",
    country: "India",
    iata_code: "GAY",
    icao_code: "VEGY",
    __v: 0,
  },
  {
    coordinates: {
      latitude: 21.1141,
      longitude: 72.7418,
    },
    additional_info: {
      timezone: "IST",
      elevation: 5,
    },
    _id: "6514309e348f6fafa1b8661b",
    name: "Surat Airport",
    city: "Surat",
    country: "India",
    iata_code: "STV",
    icao_code: "VASU",
    __v: 0,
  },
  {
    coordinates: {
      latitude: 21.1804,
      longitude: 81.7388,
    },
    additional_info: {
      timezone: "IST",
      elevation: 311,
    },
    _id: "6514309e348f6fafa1b8661c",
    name: "Raipur Airport",
    city: "Raipur",
    country: "India",
    iata_code: "RPR",
    icao_code: "VERP",
    __v: 0,
  },
  {
    coordinates: {
      latitude: 32.6891,
      longitude: 74.8377,
    },
    additional_info: {
      timezone: "IST",
      elevation: 291,
    },
    _id: "6514309e348f6fafa1b8661d",
    name: "Jammu Airport",
    city: "Jammu",
    country: "India",
    iata_code: "IXJ",
    icao_code: "VIJU",
    __v: 0,
  },
];
